services:
  mjakazi-connect-mockup:
    image: ghcr.io/m6o4solutions/mjakazi-connect-mockup:latest
    container_name: mjakazi-connect-mockup
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mjakazi-connect-mockup.rule=Host(`mockup.mjakaziconnect.co.ke`)"
      - "traefik.http.routers.mjakazi-connect-mockup.entrypoints=websecure"
      - "traefik.http.routers.mjakazi-connect-mockup.tls.certresolver=letsencrypt"
      - "traefik.http.services.mjakazi-connect-mockup.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
    name: traefik-network
